theme: jekyll-theme-minimal
title: favorite
description: 一些搜集來的喜好網站分享
navigation:
  - title: biography
    url: https://zenkarsha.github.io/biography/
  - title: poetry
    url: https://zenkarsha.github.io/poetry/
  - title: muse
    url: https://zenkarsha.github.io/muse/
  - title: whisper
    url: https://zenkarsha.github.io/whisper/
  - title: works
    url: https://zenkarsha.github.io/works/
  - title: blog
    url: https://zenkarsha.github.io/blog/
